# Production profile
server:
  port: 8093

downstream-services:
  services:
    ap-services:
      base-url: https://api.example.com/v2
      timeout: 30

logging:
  level:
    com.lca.productionsupport: INFO
    org.springframework.web: WARN

