# Production profile
server:
  port: 8093

downstream-services:
  services:
    ap-services:
      base-url: https://localhost:8091
      timeout: 30

logging:
  level:
    com.lca.productionsupport: INFO
    org.springframework.web: WARN

